### ISSUE TITLE
/Integrated/Windows/笔记/认证.md 错误

### ISSUE THREAD

**Issue by shisan111** [ffffffff0x/1earn#11]
1050行，【KDC 在收到这个 `KBR_AP_REQ`请求的时候】，应该是`KBR_TGS_REQ`吧

**Comment by No-Github** [comment]
多谢师傅指正，正好发现流程图里的箭头也画反了，一会修改

**Comment by No-Github** [comment]
已经更新上去了，多谢师傅的反馈👍，后面师傅发现了其他的问题可以在提哈
