### ISSUE TITLE
IoT Binaries

### ISSUE THREAD

**Issue by FlyingFatty** [ffffffff0x/1earn#5]
Thx 4 your all meterials.
I want to study IoT, and I read lots of your writeups.
There are lots of firewares or binaries I can not download from the Internet.
For example, DWR-932_fw_revB_2_02_eu_en_20150709.zip
Would you mind to share it online?
Thx.

**Comment by No-Github** [comment]
Sorry, I don't have a backup, it seems that dlink ftp server is no longer accessible

But you can download the DWR-932_fw_revB_2_02_eu_en_20150709.zip from the following URL
* https://drivers.softpedia.com/get/Router-Switch-Access-Point/D-Link/D-Link-DWR-932-Rev-B1-Router-Firmware-2-02.shtml
