### ISSUE TITLE
没有二进制代码么

### ISSUE THREAD

**Issue by kanxue660** [ffffffff0x/1earn#8]
逆向部分光有结果，没有对应的程序么？

**Comment by No-Github** [comment]
抱歉，我这边也没有保存,不过如果你需要找案例学习逆向的话，我比较推荐你看看 [buuctf](https://buuoj.cn/) 平台上的逆向题目，从入门到进阶的各种都有，学习起来也很方便

**Comment by No-Github** [comment]
如果没有其他问题，这个issue我就先关闭了，后面师傅有其他好的意见或问题可以在提哈
